apiVersion: batch/v1
kind: CronJob
metadata:
  name: airflow-audit-cronjob
  namespace: airflow
  labels:
    app: airflow-audit-cronjob
spec: 
  schedule: "0 8 * * *" # Run every day at 8am UTC (4am EST)
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: airflow-script-container
            image: ghcr.io/rosecape/airflow-audit:latest
            env:
            - name: AIRFLOW_API_USERNAME
              valueFrom:
                secretKeyRef:
                  name: airflow-api-creds
                  key: username
            - name: AIRFLOW_API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: airflow-api-creds
                  key: password
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: slack-webhook-creds
                  key: url
          restartPolicy: OnFailure